# Generated by Django 4.2.11 on 2024-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, unique=True, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='covers/{self.pk}/', verbose_name='Обложка')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('description', models.TextField(default='Coming Soon', verbose_name='Описание')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'db_table': 'games',
                'ordering': ('title',),
            },
        ),
    ]
