# Generated by Django 4.2.11 on 2024-05-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_games', '0003_wishlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'ordering': ('id',), 'verbose_name': 'Список Желаемоего', 'verbose_name_plural': 'Списки Желаемого'},
        ),
    ]
